enum Baby {
  activityAndEntertainment,
  apparelAndAccessories,
  babyAndTodlerToys,
  babyCare,
  babyStationery,
  carSeatsAndAccessories,
  diapering,
  feeding,
  gifts,
  nursery,
  pregnancyAndMaternity,
  pottyTraining,
  strollersAndAccessories,
  travelGear,
}