enum Computers {
  computerAccessories,
  computerComponents,
  dataStorage,
  externalComponents,
  laptopAccessories,
  monitors,
  networkinProducts,
  powerStrips,
  surgeProtectors,
  printers,
  scanners,
  servers,
  tabletAccessories,
}