enum HealthHousehold {
  babyAndChildCare,
  householdSupplies,
  medicalSuppliesAndEquipment,
  sexualWellness,
  sportsNutrition,
  stationeryAndGiftWrapping,
  visionCare,
  vitaminsAndDietarySupplements,
  wellnessAndRelaxation,
  feminineCare,
  electricShavers,
  razorsAndBlades,
  bathAndBody,
  weightManagement,
  proteinsAndFitness,
}